name: "Setup Environment"
description: "Set up the pre-compiled environment"

runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache Foundry toolchain
      uses: actions/cache@v2
      with:
        path: ~/.foundry
        key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}
        restore-keys: |
          ${{ runner.os }}-foundry-

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly-c161c7c9ed5f939adca5e88ff279654ae37c4a3d

    - name: Clean Contracts
      run: forge clean
      shell: bash

    - name: Compile Proposals
      run: forge compile --contracts proposals/
      shell: bash

    - name: Compile Contracts
      run: forge build
      shell: bash
