name: "Setup Environment"
description: "Set up the pre-compiled environment"

runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache Foundry toolchain
      uses: actions/cache@v2
      with:
        path: ~/.foundry
        key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}
        restore-keys: |
          ${{ runner.os }}-foundry-

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly-2442e7a5fc165d7d0b022aa8b9f09dcdf675157b

    - name: Add forge to PATH
      run: echo "$HOME/.foundry/bin" >> $GITHUB_PATH
      shell: bash

    # Verify forge installation path
    - name: Check forge installation
      run: |
        echo "Forge binary path:"
        ls -l $HOME/.foundry/bin/forge
        echo "Contents of ~/.foundry/bin:"
        ls -l $HOME/.foundry/bin
        echo "Verify forge version"
        forge --version
      shell: bash

    - name: Clean Contracts
      run: forge clean
      shell: bash

    - name: Compile Contracts
      run: forge build
      shell: bash
