name: Base Integration Tests - Part 2

on: [pull_request]

env:
    BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}

jobs:
  run-base-tests:
    name: base-integration-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Base Mainnet Integration Tests
        run: time forge test --match-contract LiveSystemBaseTest --fork-url base
          -vvv --ffi
