name: Foundry Eth chainlink oracle integration tests

on: [pull_request]

env:
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}

jobs:
  run-eth-mainnet-tests:
    name: eth-oracle-integration-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Integration Test Contracts
        run: time forge test --match-contract ChainlinkCompositeOracleIntegrationTest --fork-url $BASE_RPC_URL
