name: Ethereum

on: [pull_request]

env:
  ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}

jobs:
  run-eth-mainnet-tests:
    name: Oracle Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Run Integration Test
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 10
           max_attempts: 3
           command: time forge test --match-contract ChainlinkCompositeOracleIntegrationTest --fork-url ethereum
