name: Invariant 

on: [pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  invariant-tests:
    name: Invariant Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Run Invariant Test 
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           max_attempts: 3
           command: time forge test -vvv --match-contract Invariant


