name: Linter

on: [pull_request]

jobs:
    lint:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Check out the repo"
              uses: "actions/checkout@v3"
              with:
                  submodules: "recursive"

            - name: "Install Node.js"
              uses: "actions/setup-node@v3"
              with:
                  node-version: "lts/*"

            - name: "Install the Node.js dependencies"
              run: "npm install"

            - name: "Lint the contracts"
              id: lint
              run: |
                  if npm run lint; then
                      echo "LINT_STATUS=passed" >> $GITHUB_ENV
                  else
                      echo "LINT_STATUS=failed" >> $GITHUB_ENV
                      exit 1
                  fi

            - name: "Add lint summary"
              if: always()
              run: |
                  if [ "$LINT_STATUS" = "passed" ]; then
                      echo "## Lint result" >> $GITHUB_STEP_SUMMARY
                      echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
                  else
                      echo "## Lint result" >> $GITHUB_STEP_SUMMARY
                      echo "❌ Failed" >> $GITHUB_STEP_SUMMARY
                  fi
