name: Linter

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Install Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: "Install the Node.js dependencies"
        run: npm install

      - name: "Lint the contracts and capture output"
        id: lint
        run: |
          LINT_OUTCOME=$(npm run lint 2>&1)
          echo "::set-output name=result::${LINT_OUTCOME}"
          echo "LINT_OUTCOME<<EOF" >> $GITHUB_ENV
          echo "$LINT_OUTCOME" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: "Check for errors in lint outcome"
        if: always()
        run: |
          if grep -q "error" <<< "$LINT_OUTCOME"; then
              echo "## Lint result" >> $GITHUB_STEP_SUMMARY
              echo "❌ Failed" >> $GITHUB_STEP_SUMMARY
              exit 1
          else
              echo "## Lint result" >> $GITHUB_STEP_SUMMARY
              echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
          fi
