name: Foundry Eth chainlink oracle integration tests

on: [pull_request]

jobs:
  run-eth-mainnet-tests:
    name: eth-live-proposals-integration-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Integration Test Contracts
        run: time forge test --mc LiveProposalsIntegrationTest --ffi
