name: Live Proposal Integration Tests
on: [pull_request]

env:
  OP_RPC_URL: ${{secrets.OP_RPC_URL}}
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
  MOONBEAM_RPC_URL: ${{secrets.MOONBEAM_RPC_URL}}

jobs:
  run-live-proposals-integration-tests:
    name: live-proposals-integration-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Live Proposal Integration Tests
        shell: bash
        uses: nick-fields/retry@v3
        with:
           timeout_minutes: 10
           max_attempts: 3
           command: time forge test --mc LiveProposalsIntegrationTest -vvvvv

