name: Moonbeam 

on: [pull_request]

env:
  MOONBEAM_RPC_URL: ${{secrets.MOONBEAM_RPC_URL}}
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
  FOUNDRY_PROFILE: ci

jobs:
  run-moonbeam-tests:
    name: Moonbeam Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Run Integration Test
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 20
           max_attempts: 3
           command: time forge test --match-contract MoonbeamTest --fork-url moonbeam -vvv
