name: Onchain Calldata Check

on: [pull_request]

env:
  OP_RPC_URL: ${{secrets.OP_RPC_URL}}
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
  MOONBEAM_RPC_URL: ${{secrets.MOONBEAM_RPC_URL}}

jobs:
  run-tests:
    name: on-chain-calldata-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Run Test Proposal Calldata Generation
        uses: nick-fields/retry@v3
        with:
           timeout_minutes: 20
           max_attempts: 3
           command: time forge test --match-contract TestProposalCalldataGeneration \
                    -vvv --ffi --block-gas-limit 10000000000

