name: Optimism Integration Tests

on: [pull_request]

env:
  OP_RPC_URL: ${{secrets.OP_RPC_URL}}
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
  MOONBEAM_RPC_URL: ${{secrets.MOONBEAM_RPC_URL}}
  PRIMARY_FORK_ID: 2

jobs:
  run-base-tests:
    name: optimism-integration-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Integration Tests Base Mainnet
        run: time forge test --match-contract LiveSystemDeploy -vvv 
